backend:
  name: git-gateway
  branch: master
  squash_merges: true
  commit_messages:
    create: "feat: Create {{collection}} “{{slug}}” {{author-name}} [skip test]"
    update: "chore: Update {{collection}} “{{slug}}” {{author-name}} [skip test]"
    delete: "chore: Delete {{collection}} “{{slug}}” {{author-name}} [skip test]"
    uploadMedia: "chore: Upload “{{path}}” {{author-name}} [skip test]"
    deleteMedia: "chore: Delete “{{path}}” {{author-name}} [skip test]"
  preview_context: netlify/tradetrust-mainnet/deploy-preview # beta feature = https://github.com/netlify/netlify-cms/issues/2315, https://github.com/netlify/netlify-cms/issues/4812

local_backend: true

publish_mode: editorial_workflow

media_folder: "public/static/uploads"
public_folder: "/static/uploads"
